[package]
name = "poms-adapter-kraftringen"
edition.workspace = true
version.workspace = true

[[bin]]
name = "kraftringen-adapter"
path = "src/main.rs"

[dependencies]
poms-types = { path = "../../types" }
poms-adapter-sdk = { path = "../../adapter-sdk" }
poms-db = { path = "../../db" }
tokio.workspace = true
reqwest.workspace = true
serde.workspace = true
quick-xml.workspace = true
anyhow.workspace = true
chrono.workspace = true
chrono-tz.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
async-trait.workspace = true
